version: '2'
services:
  candidate:
    hostname: candidate
    image: garystafford/candidate-service:0.2.14
    ports:
    - 8097:8097/tcp
  mongodb:
    command:
    - --smallfiles
    hostname: mongodb
    image: mongo:latest
    ports:
    - 27017:27017/tcp
  voter:
    hostname: voter
    image: garystafford/voter-service:0.2.80
    ports:
    - 8099:8099/tcp
