# Deploy Voter Stack locally
# No external container dependencies

version: '3.0'

services:
  client:
    image: garystafford/voter-client:rabbitmq
    depends_on:
    - gateway
    hostname: client
    ports:
    - "9090:9090/tcp"

  gateway:
    image: garystafford/voter-api-gateway:latest
    depends_on:
    - election
    - candidate
    - voter
    hostname: voter-api-gateway
    ports:
    - "8080:8080/tcp"

  election:
    image: garystafford/election-service:rabbitmq
    depends_on:
    - mongodb
    - rabbitmq
    hostname: election
    ports:
    - "8095:8095/tcp"
    command: "java -Dspring.profiles.active=${ACTIVE_PROFILE} \
      -Dlogging.level.root=DEBUG \
      -Djava.security.egd=file:/dev/./urandom \
      -jar election/election-service.jar"

  candidate:
    image: garystafford/candidate-service:rabbitmq
    depends_on:
    - mongodb
    - rabbitmq
    hostname: candidate
    ports:
    - "8097:8097/tcp"
    command: "java -Dspring.profiles.active=${ACTIVE_PROFILE} \
      -Dlogging.level.root=DEBUG \
      -Djava.security.egd=file:/dev/./urandom \
      -jar candidate/candidate-service.jar"

  voter:
    image: garystafford/voter-service:rabbitmq
    depends_on:
    - mongodb
    - rabbitmq
    hostname: voter
    ports:
    - "8099:8099/tcp"
    command: "java -Dspring.profiles.active=${ACTIVE_PROFILE} \
      -Dlogging.level.root=DEBUG \
      -Djava.security.egd=file:/dev/./urandom \
      -jar voter/voter-service.jar"

  mongodb:
    image: mongo:latest
    command:
    - --smallfiles
    hostname: mongodb
    ports:
    - "27017:27017/tcp"
    volumes:
    - demo_data_vol:/data/db

  rabbitmq:
    image: rabbitmq:management-alpine
    hostname: rabbitmq
    ports:
    - "5672:5672/tcp"
    - "15672:15672/tcp"
    volumes:
    - demo_data_vol:/data/db

volumes:
  demo_data_vol:
