server:
  port: 8099
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/voters
logging:
  level:
    root: INFO
info:
  java:
    source: ${java.version}
    target: ${java.version}
management:
  info:
    git:
      mode: full
    build:
      enabled: true
---
spring:
  profiles: aws-production
  data:
    mongodb:
      uri: mongodb://10.0.1.6:27017/voters
logging:
  level:
    root: WARN
management:
  info:
    git:
      enabled: false
    build:
      enabled: false
endpoints:
  sensitive: true
  enabled: false
  info:
    enabled: true
  health:
    enabled: true
---
spring:
  profiles: docker-local
  data:
    mongodb:
      uri: mongodb://mongodb:27017/voters
---
spring:
  profiles: docker-production
  data:
    mongodb:
      uri: mongodb://mongodb:27017/voters
logging:
  level:
    root: WARN
management:
  info:
    git:
      enabled: false
    build:
      enabled: false
endpoints:
  sensitive: true
  enabled: false
  info:
    enabled: true
  health:
    enabled: true
