azure:
  service-bus:
    connection-string: sensitive_set_get_from_env_var
endpoints:
  enabled: true
  sensitive: false
info:
  java:
    source: "${java.version}"
logging:
  level:
    root: INFO
management:
  info:
    build:
      enabled: true
    git:
      mode: full
server:
  port: 8095
  context-path: /voter
spring:
  application:
    name: Voter Service
  data:
    mongodb:
      uri: <sensitive_set_get_from_env_var>
---
server:
  port: 8080
spring:
  profiles: kub-aks
