# Deploy Voter Stack to Docker for AWS Swarm (swarm mode)

version: '3.0'

services:
  visualizer:
    image: manomarks/visualizer:latest
    hostname: visualizer
    ports:
    - "5001:8080/tcp"
    networks:
    - demo_overlay_net
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
      placement:
        constraints:
        - node.role == manager
    environment:
      SERVICE_NAME: visualizer
      SERVICE_TAGS: monitoring

networks:
  demo_overlay_net:

volumes:
  demo_data_vol:
