version: '3.0'

services:
  voter-api-gateway:
    image: garystafford/voter-api-gateway:latest
    depends_on:
    - voter
    - candidate
    hostname: voter-api-gateway
    ports:
    - "8080:8080/tcp"
    networks:
    - demo_overlay_net

  candidate:
    image: garystafford/candidate-service:rabbitmq
    depends_on:
    - mongodb
    - rabbitmq
    hostname: candidate
    ports:
    - "8097:8097/tcp"
    networks:
    - demo_overlay_net
    command: "java -Dspring.profiles.active=${ACTIVE_PROFILE} \
      -Dlogging.level.root=DEBUG \
      -Djava.security.egd=file:/dev/./urandom \
      -jar candidate/candidate-service.jar"

  voter:
    image: garystafford/voter-service:rabbitmq
    depends_on:
    - mongodb
    - rabbitmq
    hostname: voter
    ports:
    - "8099:8099/tcp"
    networks:
    - demo_overlay_net
    command: "java -Dspring.profiles.active=${ACTIVE_PROFILE} \
      -Dlogging.level.root=DEBUG \
      -Djava.security.egd=file:/dev/./urandom \
      -jar voter/voter-service.jar"

  mongodb:
    image: mongo:latest
    command:
    - --smallfiles
    hostname: mongodb
    ports:
    - "27017:27017/tcp"
    networks:
    - demo_overlay_net
    volumes:
    - demo_data_vol:/data/db

  rabbitmq:
    image: rabbitmq:management-alpine
    hostname: rabbitmq
    ports:
    - "5672:5672/tcp"
    - "15672:15672/tcp"
    networks:
    - demo_overlay_net
    volumes:
    - demo_data_vol:/data/db

networks:
  demo_overlay_net:
    external: true

volumes:
  demo_data_vol:
    external: true
